name: JavaScript Unit Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  nodejs-unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20, 22]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install python virtual environment
        if: ${{ matrix.os == 'macos-latest' }}
        run: python3 -m venv .venv && source .venv/bin/activate

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run test
        run: npm test
